// <auto-generated />
namespace admin_mode.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ADDED_ADDRESS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADDED_ADDRESS));
        
        string IMigrationMetadata.Id
        {
            get { return "201509290949495_ADDED_ADDRESS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
